---
title: "Prima squadra"
format:
  html:
    theme: darkly
    css: styles.css
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, error=TRUE}

source("code/data_generation_ft.R")

```

Questa è la sezione dedicata alla **prima squadra**.

## Portieri
- K. Ferrara 1  
- C. Maianti 12  

## Difensori
- [A. Arpini](GiocatoriFT/arpini.html)
- [S. Azzali](GiocatoriFT/azzali.html) 
- [V. Camilleri](GiocatoriFT/camilleri.html) 
- [E. Maccherini](GiocatoriFT/maccherini.html)  
- [L. Niculae](GiocatoriFT/niculae.html)
- [M. Vailati](GiocatoriFT/vailati.html)

## Centrocampisti
- [N. Abba](GiocatoriFT/abba.html)
- [J. Cerasani](GiocatoriFT/cerasani.html)
- [T. Erman](GiocatoriFT/erman.html)
- [L. Gramignoli](GiocatoriFT/gramignoli.html)
- [A. Latini](GiocatoriFT/latini.html)
- [J. Mozzanica](GiocatoriFT/mozzanica.html)
- [R. Pavesi](GiocatoriFT/pavesi.html)
- [T. Serioli](GiocatoriFT/serioli.html)
- [R. Tomella](GiocatoriFT/tomella.html)
- [T. Valdameri](GiocatoriFT/valdameri.html)

## Attaccanti
- [E. Neci](GiocatoriFT/neci.html)
- [G. Recino](GiocatoriFT/recino.html)
- [D. Fenotti](GiocatoriFT/fenotti.html) 
- [M. Varisco](GiocatoriFT/varisco.html)

