---
title: "Under 16"
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    smooth-scroll: true
    fig-format: svg
    fig-dpi: 320
    page-layout: article
execute:
  echo: false
  message: false
  warning: false
---



```{r, echo=FALSE, message=FALSE, warning=FALSE, error=TRUE}

source("code/data_generation_unico.R")

```


Questa è la sezione dedicata alla **Under 17**.

## Portieri
- A. Mazzucchetti

## Difensori
- [L. Diana](GiocatoriU16/diana.html)
- Baldajack 
- [A. De maria](GiocatoriU16/demaria.html) 
- [D. Constantin](GiocatoriU16/constantin.html)
- [G. Groppelli](GiocatoriU16/groppelli.html) 
- [D. Martinelli](GiocatoriU16/martinelli.html)


## Centrocampisti
- [A. Oitha](GiocatoriU16/oitha.html)
- [T. Anelli](GiocatoriU16/anelli.html) 
- [C. Biondi](GiocatoriU16/biondi.html) 
- [J. Onoh](GiocatoriU16/onoh.html)
- [G. Testa](GiocatoriU16/testa.html) 
- [R. Gallarati](GiocatoriU16/gallarati.html) 


## Attaccanti
- [M. Bardella](GiocatoriU16/bardella.html) 
- [D. Cangianiello](GiocatoriU16/cangianiello.html) 
- [O. Diop](GiocatoriU16/diop.html)
- [W. Lazzari](GiocatoriU16/lazzari.html)
- [L. Piovesan](GiocatoriU16/piovesan.html) 
- [V. Zucchi](GiocatoriU16/zucchi.html) 

# Analisi All Time

