---
title: "N. Abba"
format:
  html:
    theme: darkly
    css: styles.css
---

## Centrocampista


# Statistiche All Time 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportUnoNew.R")
source("../code/ReportDueNew.R")
source("../code/lista_squadre.R")
source("../code/Temi_grafici.R")
source("../code/fisico_vs_tecnica.R")
source("../code/comparison_U17_vs_FT.R")
source("../code/player_wheel.R")
source("../code/run_dynamics.R")

df_ft <- read_excel(here("data", "CremaFT_2401.xlsx"))

cph <- prep_physical_context(df_ft, players = players_ft)

ctx_session <- prep_skill_context(df_ft, players = players_ft, data_type = "session")
ctx_pf <- prep_skill_context(df_ft, players = players_ft, data_type = "pf")
ctx_matches <- prep_skill_context(df_ft, players = players_ft, data_type = "match", matches_list = match_ft)


player_sel <- "N. Abba"
plot_phy_tec_player(player_sel)
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_fisico(player_sel, cph)
```


::: {.panel-tabset}
# Full Sessions
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico(player_sel, ctx_session)
```

# Partita Finale Allenamento
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico(player_sel, ctx_pf)
```

# Partite Ufficiali
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico(player_sel, ctx_matches)
```

:::

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-format: png
#| fig-dpi: 320
#| fig-bg: "#0b0b0b"
#| fig-width: 7
#| fig-height: 7
#| out-width: "85%"

plot_player_wheel(pcts, player_sel)


```

# Trend di forma

```{r, echo=FALSE, message=FALSE, warning=FALSE}
trend_fisico(player_sel, cph)

```

# Trend tecnico

```{r, echo=FALSE, message=FALSE, warning=FALSE}
trend_tecnico_indici(player_sel, ctx_session)
trend_tecnico_possesso(player_sel, ctx_session)
trend_tecnico_piede(player_sel, ctx_session)

```

# Giocatore simile nelle giovanili 

::: {.panel-tabset}
# Valori Fisici
```{r, echo=FALSE, message=FALSE, warning=FALSE}
find_most_similar_u17(player_sel, 
                      ft_data_phy, u17_data_phy, return_plot = T)$plot
```

# Valori Tecnici 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
find_most_similar_u17(player_sel, 
                      ft_data_tec, u17_data_tec, return_plot = T)$plot
```

:::

# Dinamica di corsa

::: {.panel-tabset}
# Contact Duration
```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_hid_box_kpi(df_dynamic_hid_match, player_sel, metric = "HCD")

```

# Flight Duration
```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_hid_box_kpi(df_dynamic_hid_match, player_sel, metric = "HFD")

```

# Stride Length
```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_hid_box_kpi(df_dynamic_hid_match, player_sel, metric = "HSL")


```


:::

## Valori anomali

::: {.panel-tabset}
# Contact Duration
```{r, echo=FALSE, message=FALSE, warning=FALSE}
gt_hid_outlier_table(df_dynamic_hid_match, player_sel, metric = "HCD", top_n = 20)

```

# Flight Duration
```{r, echo=FALSE, message=FALSE, warning=FALSE}
gt_hid_outlier_table(df_dynamic_hid_match, player_sel, metric = "HFD", top_n = 20)

```

# Stride Length
```{r, echo=FALSE, message=FALSE, warning=FALSE}
gt_hid_outlier_table(df_dynamic_hid_match, player_sel, metric = "HSL", top_n = 20)

```
:::

