---
---
title: "R. De Martino"
format:
  html:
    theme: darkly
    css: styles.css
---

## Attaccante


# Statistiche All Time 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportUno.R")

report_fisico("R. De Martino")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportDue.R")
source("../code/partita_finale.R")

player_sel <- "R. De Martino"

```

::: {.panel-tabset}
# Full Sessions
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico(player_sel)
```

# Partita Finale 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico_pf(player_sel)
```

:::

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-format: png
#| fig-dpi: 320
#| fig-bg: "#0b0b0b"
#| fig-width: 7
#| fig-height: 7
#| out-width: "85%"

source("../code/player_wheel.R")
plot_player_wheel(pcts, "R. De Martino")


```

# Trend di forma

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportUno.R")

trend_fisico_giocatore("R. De Martino")

```

# Trend tecnico

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportDue.R")

trend_tecnico_indici("R. De Martino")
trend_tecnico_possesso("R. De Martino")
trend_tecnico_piede("R. De Martino")

```

title: "demartino"
---

