---
title: "L. Gramignoli"
format:
  html:
    theme: darkly
    css: styles.css
---

## Centrocampista


# Statistiche All Time 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportUno.R")

report_fisico("L. Gramignoli")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportDue.R")
source("../code/partita_finale.R")

player_sel <- "L. Gramignoli"

```

::: {.panel-tabset}
# Full Sessions
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico(player_sel)
```

# Partita Finale 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_tecnico_pf(player_sel)
```

:::

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-format: png
#| fig-dpi: 320
#| fig-bg: "#0b0b0b"
#| fig-width: 7
#| fig-height: 7
#| out-width: "85%"

source("../code/player_wheel.R")
plot_player_wheel(pcts, "L. Gramignoli")


```

# Trend di forma

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportUno.R")

trend_fisico_giocatore("L. Gramignoli")

```

# Trend tecnico

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/ReportDue.R")

trend_tecnico_indici("L. Gramignoli")
trend_tecnico_possesso("L. Gramignoli")
trend_tecnico_piede("L. Gramignoli")

```

# Giocatore simile nelle giovanili 

::: {.panel-tabset}
# Valori Fisici
```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("../code/comparison_U17_vs_FT.R")
find_most_similar_u17(player_sel, 
                      ft_data_phy, u17_data_phy, return_plot = T)$plot
```

# Valori Tecnici 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
find_most_similar_u17(player_sel, 
                      ft_data_tec, u17_data_tec, return_plot = T)$plot
```

:::
